FROM node:alpine AS builder

COPY src /app/src

COPY public /app/public

COPY package.json package-lock.json /app/

RUN cd /app/ && npm install --no-optional --development && npm install -g serve && npm cache clean --force

RUN cd /app/ && npm run build

# Fetching the latest nginx image
FROM nginx

# Copying built assets from builder
COPY --from=builder /app/build /usr/share/nginx/html

# Copying our nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /app

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]