apiVersion: v1
kind: Service
metadata:
  name: zipnews-ui-svc
  labels:
    app: zipnews-ui
spec:
  ports:
    - name: zipnews-ui
      protocol: "TCP"
      port: 3000
      targetPort: 80
  selector:
    app: zipnews-ui
  type: NodePort