FROM python:3.8

COPY requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

COPY src /app/src

COPY commands.sh /app/commands.sh

WORKDIR /app

ENTRYPOINT [ "./commands.sh" ]